### ISSUE TITLE
bamtolas errors out

### ISSUE THREAD

**Issue by govinda-kamath** [gt1/lastools#1]
I was trying to convert a bam file to a las file for downstream processing. However, I see the following error. Is there any fix to this?

```
govinda@saraswati$ bamtolas overlaps.las reads.pb.fasta < overlaps.bam
[E] file contains unhadled CIGAR operation M

/usr/local/lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x54)[0x7ff968dd5a94]
bamtolas(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x425b80]
bamtolas(bamtolas(libmaus2::util::ArgParser const&, libmaus2::util::ArgInfo const&)+0x1722)[0x424042]
bamtolas(main+0x1de)[0x42074e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7ff967ba1f45]
bamtolas()[0x4208bf]
```

I'd appreciate any help wrt this.

**Comment by gt1** [comment]
bamtolas does not support the cigar operation M (match or mismatch), it requires the more precise = (match) and X (mismatch) operators. There is bamrecalculatecigar in biobambam2 to produce a suitable input file. Try something like

samtools faidx reference.fa
bamrecalculatecigar reference=reference.fa < overlaps.bam > overlaps_eq_diff.bam

Then feed overlaps_eq_diff.bam into bamtolas.

**Comment by govinda-kamath** [comment]
The bam file I had was a read-to-read mapping file obtained from minimap2. Would it be possible to fix that as well?

**Comment by svm-zhang** [comment]
Hello @govinda-kamath,

I had the same problem as you, and when I specified my pacbio raw reads (the fasta file) as the reference, bamrecalculatecigar issued a "SEG FAULT". So I ended up writing my own python cigar converter using pysam, and it worked (not quite efficiently though). If you'd like to try, I could push it a repo.

Simo

**Comment by govinda-kamath** [comment]
Hi Simo,

Thanks a lot. If you pushed your code to a repo, it would be very nice. We're still looking to do this and were thinking of writing script of our own. 

Govinda.

**Comment by gt1** [comment]
Hi,

could I get an example SAM file and reference bamrecalculatecigar crashes on? It should just generally work.

@govinda-kamath : speeking of the minimap2 case, what would you want to be fixed?

**Comment by govinda-kamath** [comment]
@gt1 : As @svm-zhang  mentioned, bamrecalculate cigar gives a segmentation fault. I thought this was due to the fact that I was using reads instead of a reference. 

The problem can be reproduced using this read file: https://www.dropbox.com/s/dhwxixs0rli8iy8/reads.pb.fasta.gz?dl=0

I don't know a good way to upload the 3Gb bam file, but this sequence of commands should reproduce the error. (Let me know if you know a way to share the bam and I'll be happy to share it)

```
govinda@saraswati$ gunzip reads.pb.fasta.gz
govinda@saraswati$ minimap2 -ax ava-pb reads.pb.fasta reads.pb.fasta > overlaps.sam
[M::mm_idx_gen::61.643*1.00] collected minimizers
[M::mm_idx_gen::67.028*1.15] sorted minimizers
[M::main::67.028*1.15] loaded/built the index for 82590 target sequence(s)
[M::mm_mapopt_update::79.416*1.12] mid_occ = 51; max_occ = 186
[M::mm_idx_stat] kmer size: 19; skip: 5; is_HPC: 1; #seq: 82590
[M::mm_idx_stat::81.050*1.12] distinct minimizers: 59410241 (78.37% are singletons); average occurrences: 1.762; average spacing: 4.175
govinda@saraswati$ samtools view -bS overlaps.sam > overlaps.bam
govinda@saraswati$ samtools faidx reads.pb.fasta
govinda@saraswati$ bamrecalculatecigar reference=reads.pb.fasta < overlaps.bam > overlaps_eq_diff.bam
Segmentation fault
```

**Comment by svm-zhang** [comment]
@gt1: Besides what @govinda-kamath has said, I think it might be also because minimap2, for reads mapped, does not give their seq in its BAM file. It does so for unmapped reads. This observation is made for my small virus dataset. And if you wonder what dataset I used, you can find it here: [(https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/FALCON-Walkthrough:-Assembling-Lambda-and-Analyzing-Output)](url). The minimap2 command line I used to generate my SAM file is:

`minimap2 -x ava-pb -a lambda_filtered_subreads.fasta lambda_filtered_subreads.fasta > lambda.raw.sam`

And then I simply followed standard procedure to convert from sam to bam using samtools.

I hope this might offer a bit help for you to debug. Your lastools is very useful :)

@govinda-kamath I will push it once I get back to my desk :) 

Simo

**Comment by svm-zhang** [comment]
@govinda-kamath it is here: [https://github.com/svm-zhang/pb_ec](url). It is "not-quick but dirty" code :)

**Comment by govinda-kamath** [comment]
Thanks @svm-zhang. Will try it out.

**Comment by gt1** [comment]
The bamrecalculatecigar crash seems due to undefined query sequence fields in the SAM file produced by minimap2. I'll see what I can do about it.

**Comment by svm-zhang** [comment]
@gt1 Thanks very much!

**Comment by gt1** [comment]
I would suggest the following to process minimap2 SAM files:

```
# sort by query name (see bamsormadup in biobambam2)
bamsormadup SO=queryname inputformat=sam < minimap.sam > minimap_qn.bam
# sort reads by query name (see sortfasta in daccord)
sortfasta < reads.fasta >reads_qn.fasta
# inject query sequences into BAM file (see bamfillquery in biobambam2)
bamfillquery < minimap_qn.bam reads_qn.fasta >minimap_qn_filled.bam
# sort
bamsormadup < minimap_qn_filled.bam > minimap_qn_filled_sorted.bam
# replace M cigar operators by =/X (bamrecalculatecigar in biobambam2)
bamrecalculatecigar reference=reads.fasta < minimap_qn_filled_sorted.bam > minimap_qn_filled_sorted_eqdif.bam
# convert to LAS
bamtolas minimap_qn_filled_sorted_eqdif.las reads.fasta < minimap_qn_filled_sorted_eqdif.bam
```

**Comment by gt1** [comment]
I'll close this issue. It was essentially never about a bug in bamtolas, the program just does not support the M cigar operator. There are programs out there for removing that operator as mentioned above.
