### ISSUE TITLE
paf to las?

### ISSUE THREAD

**Issue by ilanshom** [gt1/lastools#2]
Hi! I'm one of the authors of HINGE, and our pipeline is based on las. Do you happen to have a paf2las converter by any chance? Are you planning on having one? Thanks!

**Comment by gt1** [comment]
If the PAF file is alignment based, this may be feasible. However I do not see a way to check this from the file format.

**Comment by gt1** [comment]
The latest release has a new program called paftolas . The command line is

```
paftolas out.las in.fasta <in.paf
```

This version does not support asymmetric input files (yet), i.e. such where the query and target sequences are drawn from different pools.

It should work with approximate and alignment based PAF files though.

**Comment by ilanshom** [comment]
Cool! Thank you, we'll check it out.
